version: '3.8'
services:
    app:
        build:
            context: .
            args:
                - USER_ID=${UID:-1000}
                - GROUP_ID=${GID:-1000}
        container_name: locker_system
        ports:
            -   8002:8000
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - .:/var/www
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/database/database.sqlite
        networks:
            - locker_system

networks:
    locker_system:
        driver: bridge
